import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runDemo } from "./run.js";

/**
 * `pnpm docs:demo` writes `docs/DEMO_SCRIPT.md`.
 *
 * Generated rather than written, because a demo script kept in a document drifts
 * from the product within a week and the first person to notice is a judge
 * watching the video next to the repository. Every spoken line below came out of
 * a tool result during this run, over Streamable HTTP, and every timing is that
 * call's own.
 */

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

const PREAMBLE = `# The demo, beat by beat

**Generated by \`pnpm docs:demo\`. Do not edit.** Every line CIRCA says below is
the \`content\` of a real MCP tool result from a real run over Streamable HTTP,
and every timing is that call's own. Regenerate it and the numbers move with the
product.

The arc is the argument. The first comparison cannot decompose the price
difference, because the contractor's quote is one number for a paragraph of work.
CIRCA says so, and says what would make it answerable. The customer asks for it
itemised, and the same call, on the same code, returns the decomposition. The
product's advice changed what the product could compute. That beat is the demo
and it is not cut for time.

Run it yourself:

\`\`\`bash
pnpm demo          # the whole arc
pnpm demo --tour   # slower, with the reasoning printed
pnpm simulator:dev # the same arc with the Echo Show card beside the transcript
\`\`\`

---

`;

async function main(): Promise<void> {
  const recorded = await runDemo();
  const lines: string[] = [PREAMBLE];

  let beatNumber = 0;
  for (const entry of recorded) {
    beatNumber += 1;
    const { beat, speech, payload, ms } = entry;

    if (beat.caption) lines.push(`### ${beat.caption}\n`);
    lines.push(`**${beatNumber}. \`${beat.tool}\`**  ·  ${ms.toFixed(0)} ms\n`);
    if (beat.said) lines.push(`> **You** — ${beat.said}\n`);
    lines.push(`**CIRCA** — ${speech}\n`);

    const rows = (payload["rows"] as { label: string; value: string; attention?: boolean }[] | undefined) ?? [];
    if (rows.length > 0) {
      lines.push("| | |");
      lines.push("|---|---|");
      for (const row of rows) {
        lines.push(`| ${row.label} | ${row.attention ? `**${row.value}**` : row.value} |`);
      }
      lines.push("");
    }

    const refusal = payload["refusal"] as string | undefined;
    if (refusal) lines.push(`> ${refusal}\n`);
    if (beat.note) lines.push(`*${beat.note}*\n`);
    lines.push("---\n");
  }

  const total = recorded.reduce((sum, r) => sum + r.ms, 0);
  const slowest = [...recorded].sort((a, b) => b.ms - a.ms)[0]!;
  lines.push(
    `${recorded.length} tool calls, ${total.toFixed(0)} ms in total, slowest \`${slowest.beat.tool}\` at ${slowest.ms.toFixed(0)} ms.\n`,
  );

  const out = path.join(REPO_ROOT, "docs/DEMO_SCRIPT.md");
  await writeFile(out, `${lines.join("\n")}`, "utf8");
  process.stdout.write(`wrote ${out}\n`);
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
  process.exit(1);
});
